<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="95" started-at="2018-07-06T05:00:05Z" finished-at="2018-07-06T05:00:05Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="95" started-at="2018-07-06T05:00:05Z" finished-at="2018-07-06T05:00:05Z">
      <class name="com.sample.testscripts.SampleTest">
        <test-method status="PASS" signature="startBeforeTest()[pri:0, instance:com.sample.testscripts.SampleTest@5622fdf]" name="startBeforeTest" is-config="true" duration-ms="17" started-at="2018-07-06T10:30:05Z" finished-at="2018-07-06T10:30:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startBeforeTest -->
        <test-method status="PASS" signature="test1()[pri:0, instance:com.sample.testscripts.SampleTest@5622fdf]" name="test1" duration-ms="10" started-at="2018-07-06T10:30:05Z" finished-at="2018-07-06T10:30:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="endAfterTest()[pri:0, instance:com.sample.testscripts.SampleTest@5622fdf]" name="endAfterTest" is-config="true" duration-ms="3" started-at="2018-07-06T10:30:05Z" finished-at="2018-07-06T10:30:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endAfterTest -->
        <test-method status="PASS" signature="startBeforeTest()[pri:0, instance:com.sample.testscripts.SampleTest@5622fdf]" name="startBeforeTest" is-config="true" duration-ms="0" started-at="2018-07-06T10:30:05Z" finished-at="2018-07-06T10:30:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startBeforeTest -->
        <test-method status="FAIL" signature="test2()[pri:0, instance:com.sample.testscripts.SampleTest@5622fdf]" name="test2" duration-ms="5" started-at="2018-07-06T10:30:05Z" finished-at="2018-07-06T10:30:05Z">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Method SampleTest.test2()[pri:0, instance:com.sample.testscripts.SampleTest@5622fdf] should have thrown an exception of type class java.lang.RuntimeException]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Method SampleTest.test2()[pri:0, instance:com.sample.testscripts.SampleTest@5622fdf] should have thrown an exception of type class java.lang.RuntimeException
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:89)
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1424)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:703)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="PASS" signature="endAfterTest()[pri:0, instance:com.sample.testscripts.SampleTest@5622fdf]" name="endAfterTest" is-config="true" duration-ms="1" started-at="2018-07-06T10:30:05Z" finished-at="2018-07-06T10:30:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endAfterTest -->
        <test-method status="PASS" signature="startBeforeTest()[pri:0, instance:com.sample.testscripts.SampleTest@5622fdf]" name="startBeforeTest" is-config="true" duration-ms="1" started-at="2018-07-06T10:30:05Z" finished-at="2018-07-06T10:30:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startBeforeTest -->
        <test-method status="SKIP" signature="test3()[pri:0, instance:com.sample.testscripts.SampleTest@5622fdf]" name="test3" duration-ms="10" started-at="2018-07-06T10:30:05Z" finished-at="2018-07-06T10:30:05Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test3 test method]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test3 test method
	at com.sample.testscripts.SampleTest.test3(SampleTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
        <test-method status="PASS" signature="endAfterTest()[pri:0, instance:com.sample.testscripts.SampleTest@5622fdf]" name="endAfterTest" is-config="true" duration-ms="0" started-at="2018-07-06T10:30:05Z" finished-at="2018-07-06T10:30:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endAfterTest -->
      </class> <!-- com.sample.testscripts.SampleTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
